use_frameworks!

target 'BLHTTPClient_Example' do
  pod 'BLHTTPClient', :path => '../'

  target 'BLHTTPClient_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
